name:                advent-of-code
version:             0.1.0.0
github:              "yitsushi/advent-of-code-2019"
license:             BSD3
author:              "Balazs Nadasdi"
maintainer:          "efertone@pm.me"
copyright:           "2019 Balazs Nadasdi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yitsushi/advent-of-code-2019#readme>

dependencies:
- base >= 4.7 && < 5
- semigroups
- optparse-applicative
- directory
- text
- containers
- filepath

library:
  source-dirs: src

executables:
  advent-of-code-2019:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code

tests:
  advent-of-code-2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - hspec
    - hspec-discover

benchmarks:
  advent-of-code-2019-bench:
    main:               Bench.hs
    source-dirs:        bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - criterion
    - split
